[libraries]
assertj = "org.assertj:assertj-core:3.26.3"
nats-client = "io.nats:jnats:2.20.2"
nats-spring = "io.nats:nats-spring-boot-starter:0.6.0-3.1"
spring-boot = "org.springframework.boot:spring-boot-dependencies:3.4.0-M3"
wiremock = "org.wiremock:wiremock:3.9.1"

[bundles]
nats = [
    "nats-client",
    "nats-spring",
]

[plugins]
catalog-update = "nl.littlerobots.version-catalog-update:0.8.4"
spotless = "com.diffplug.spotless:7.0.0.BETA3"
versions = "com.github.ben-manes.versions:0.51.0"
